import './globals.css'
import type { Metadata } from 'next'
import Header from '@/components/Dashboard/Header'
import Footer from '@/components/Dashboard/Footer'
import {UserProvider} from '@/components/Providers/UserProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={""}>
        <UserProvider>
          <Header />
          {children}
          <Footer />
        </UserProvider>
      </body>
    </html>
  )
}
